version: 2
sources:
  - schema: gz_raw_data
    name : raw
    tables:
      - identifier: raw_gz_sales
        name : sales
        description: table des ventes par order_id
        
        freshness:
          error_after:
            count: 90
            period: day
        loaded_at_field: date_date
        
      - identifier: raw_gz_product
        name: product
        description: table des produits
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
                
      - identifier: raw_gz_ship
        name: ship
        description: Table des livraisons
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
              
