version: 2
sources:
  - schema: gz_raw_data
    name : raw
    tables:
      - identifier: raw_gz_sales
        name : sales
        description: table des ventes par order_id
        
        freshness:
          warn_after:
            count: 90
            period: day
          
        loaded_at_field: CAST(date_date AS timestamp)
      - identifier: raw_gz_criteo
        name: criteo

      - identifier: raw_gz_facebook
        name: facebook

      - identifier: raw_gz_bing
        name: bing

      - identifier: raw_gz_adwords
        name: adwords
      - identifier: raw_gz_product
        name: product
        description: table des produits
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
                
      - identifier: raw_gz_ship
        name: ship
        description: Table des livraisons
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null


  - schema: course17
    name: essai
    tables:  
      - identifier: gwz_sales
        name: sales_gwz
        description: table des ventes
        columns:
          - name: orders_id
            tests:
              - not_null
                





models:
  - name: int_orders_margin
    description: Marge calculée par commande
    columns:
      - name: orders_id
        description: cle de groupement de la vue
        tests:
          - unique
  - name: int_campaigns
    description: test sur la table intermédiaire des campagnes
    columns:
      - name: ads_cost
        tests:
          - not_null
      - name: impression
          - not_null
        
              



  