version: 2
sources:
  - schema: gz_raw_data
    name : raw
    tables:
      - identifier: raw_gz_sales
        name : sales
        
      - identifier: raw_gz_product
        name: product
      - identifier: raw_gz_ship
        name: ship
